### ISSUE TITLE
Replace `int*` types with `uint*` where appropriate

### ISSUE THREAD

**Issue by zanctor** [derecalliance/protobufs#24]
I suggest changing integer types to unsigned ones, where negative values are not expected (key/secret ID, nonce, versions, `ParameterRange` values, etc). This will double the range of possible values and potentially will make the process of random values generation easier.

**Comment by jorabin** [comment]
I have a feeling that signed integers were used because of there being no unsigned integer in Java and therefore ending up as a long in the Java protobuf binding.

**Comment by zanctor** [comment]
Ah, that makes sense.
Closing the issue.
