### ISSUE TITLE
Meaning of PEM encoded

### ISSUE THREAD

**Issue by jorabin** [derecalliance/protobufs#5]
is this just base 64? How should one create a PEM encoded public key? Is the SHA-384 digest a digest of the PEM encoding?

Some code examples would be very helpful. Illustrating how to use KeyPairGenerator for encryption and signature.

Rohit agreed to do this, I can't allocate the issue to him as I don't have permission.

**Comment by ehanoc** [comment]
@lbaird @rsinha @jorabin  I'll create an issue in the cryptography repo to create example compliant with [RFC-7468](https://datatracker.ietf.org/doc/html/rfc7468)
